export { default as build } from './cmd/build'
export { default as clean } from './cmd/clean'
export { default as coverage } from './cmd/coverage'
export { default as flow } from './cmd/flow'
export { default as lint } from './cmd/lint'
export { default as precommit } from './cmd/precommit'
export { default as test } from './cmd/test'
export { default as tidy } from './cmd/tidy'
